/*
 * Hello This Is Vanh
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import com.formdev.flatlaf.themes.FlatMacLightLaf;
import dao.NguoiDungDAO;
import entity.NguoiDungEntity;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import java.sql.*;
import javax.swing.*;
import static javax.swing.WindowConstants.EXIT_ON_CLOSE;
import util.Auth;
import util.JdbcHelper;
import util.Log;
import util.Msgbox;
import util.XImage;

/**
 *
 * @author Chanh Chanh
 */
public class DangNhapJFrame extends javax.swing.JFrame {

    NguoiDungDAO daoND = new NguoiDungDAO();
    PhongTroJFrame phongTroJFrame = new PhongTroJFrame();
    Connection con;
    PreparedStatement ps;
    ResultSet rs;
    Timer timer;

    public DangNhapJFrame() {
        setUndecorated(true);
        initComponents();
        init();
    }

    void KiemTraDauVao() {

        String password = new String(txtMatKhau.getPassword());
        String tenDangNhap = txtTenDangNhap.getText();
        //Kiểm tra dữ liệu nhập vào
        if (txtTenDangNhap.getText().equalsIgnoreCase("")) {
            lblCanhBao.setText("Vui lòng nhập thông tin");
            updateCanhBao();
            txtTenDangNhap.requestFocus();
        } else if (password.equalsIgnoreCase("")) {
            lblCanhBao.setText("Vui lòng nhập thông tin");
            txtMatKhau.requestFocus();
            updateCanhBao();
        } else { //xác thực người dùng và phân quyền hệ thống
            NguoiDungEntity nd = daoND.selectById(tenDangNhap);
            if (nd == null) {
                Msgbox.alert(this, "Sai Thông Tin Đăng Nhập");
            } else {
                if (nd.getMatkhau().equalsIgnoreCase(password)) {
                    if (nd.getChucVu().equalsIgnoreCase("Quản Lí")) {
                        dispose();
                        phongTroJFrame.setVisible(true);
                        phongTroJFrame.setTenDangNhapLabel(nd.getHo() + " " + nd.getTen());
                        phongTroJFrame.setChucVuLabel(nd.getChucVu());
                        Log.info(nd.getChucVu() + " đã đăng nhập");
                    } else {
                        dispose();
                        phongTroJFrame.setVisible(true);
                        phongTroJFrame.phanQuyenNguoiDung();  //là user / nhân viên thì ẩn nút Quản Lí Người Dùng
                        phongTroJFrame.setTenDangNhapLabel(nd.getHo() + " " + nd.getTen());
                        phongTroJFrame.setChucVuLabel(nd.getChucVu());
                        Log.info(nd.getHo() + " " + nd.getTen() + " đã đăng nhập");
                    }
                } else {
                    Msgbox.alert(this, "Sai Thông Tin Đăng Nhập");
                }
            }
        }
    }

    void init() {
        setLocationRelativeTo(null);
        setTitle("Chào mừng đến với Ứng dụng quản lí phòng trọ Việt Anh Ngàn Sao");
        setIconImage(XImage.getAppIcon());
        setDefaultCloseOperation(EXIT_ON_CLOSE);
    }

    void updateCanhBao() {
        int i = 2000;
        timer = new Timer(i, new ActionListener() {
            int progress = 0;

            @Override
            public void actionPerformed(ActionEvent e) {
                // Dừng timer nếu đã hoàn thành
                lblCanhBao.setText("");
                timer.stop();
            }
        });

        //chạy timer ở trên
        timer.start();
    }

    void showHideButton() {
        if (ckbShowHide.isSelected()) {
            txtMatKhau.setEchoChar((char) 0);
            ckbShowHide.setText("Hide");
        } else {
            txtMatKhau.setEchoChar('*');
            ckbShowHide.setText("Show");
        }
    }

    void openquenmk() {
        this.dispose();
        new QuenMatKhau().setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtTenDangNhap = new javax.swing.JTextField();
        btnDangNhap = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtMatKhau = new javax.swing.JPasswordField();
        lblCanhBao = new javax.swing.JLabel();
        ckbShowHide = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        txtTenDangNhap.setBackground(new java.awt.Color(239, 244, 255));
        txtTenDangNhap.setForeground(new java.awt.Color(138, 192, 240));
        txtTenDangNhap.setText("Tên đăng nhập");
        txtTenDangNhap.setBorder(null);
        txtTenDangNhap.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTenDangNhapFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTenDangNhapFocusLost(evt);
            }
        });

        btnDangNhap.setBackground(new java.awt.Color(138, 192, 240));
        btnDangNhap.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnDangNhap.setForeground(new java.awt.Color(255, 255, 255));
        btnDangNhap.setText("Đăng Nhập");
        btnDangNhap.setBorder(null);
        btnDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangNhapActionPerformed(evt);
            }
        });

        btnExit.setText("Thoát");
        btnExit.setBorder(null);
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(51, 51, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("Quên mật khẩu ?");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setText("Đăng Nhập");

        txtMatKhau.setBackground(new java.awt.Color(239, 244, 255));
        txtMatKhau.setForeground(new java.awt.Color(138, 192, 240));
        txtMatKhau.setText("123456");
        txtMatKhau.setBorder(null);

        lblCanhBao.setForeground(new java.awt.Color(255, 0, 0));

        ckbShowHide.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ckbShowHide.setText("Show");
        ckbShowHide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ckbShowHideMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ckbShowHideMousePressed(evt);
            }
        });
        ckbShowHide.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ckbShowHideKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblCanhBao, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtTenDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(ckbShowHide, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(13, 13, 13)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 4, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtTenDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ckbShowHide))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCanhBao, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btnExit)
                .addGap(97, 97, 97))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 460, 360));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Technology.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 450));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangNhapActionPerformed
        // TODO add your handling code here:
        KiemTraDauVao();
    }//GEN-LAST:event_btnDangNhapActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void ckbShowHideMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ckbShowHideMouseClicked
        showHideButton();
    }//GEN-LAST:event_ckbShowHideMouseClicked

    private void ckbShowHideMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ckbShowHideMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_ckbShowHideMousePressed

    private void ckbShowHideKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ckbShowHideKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_ckbShowHideKeyPressed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        openquenmk();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void txtTenDangNhapFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTenDangNhapFocusGained
        txtTenDangNhap.setText("");
    }//GEN-LAST:event_txtTenDangNhapFocusGained

    private void txtTenDangNhapFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTenDangNhapFocusLost

    }//GEN-LAST:event_txtTenDangNhapFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel(new FlatMacLightLaf());
        } catch (Exception e) {
            e.printStackTrace();
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DangNhapJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDangNhap;
    private javax.swing.JButton btnExit;
    private javax.swing.JCheckBox ckbShowHide;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblCanhBao;
    private javax.swing.JPasswordField txtMatKhau;
    private javax.swing.JTextField txtTenDangNhap;
    // End of variables declaration//GEN-END:variables
}
